apiVersion: v1
kind: Service
metadata:
  name: otel-grpc-go
  namespace: staging
spec:
  selector:
    app: otel-grpc-go
  ports:
    - port: 80
      targetPort: 50051
      protocol: TCP
      name: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-grpc-go
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-grpc-go
  template:
    metadata:
      labels:
        app: otel-grpc-go
    spec:
      containers:
        - name: otel-grpc-go
          image: hasannaber123/otel-grpc-go:latest
          ports:
            - containerPort: 50051
              name: grpc
              protocol: TCP
          env:
            - name: OTLP_ENDPOINT
              value: tempo.tempo:4317
            - name: OTEL_SERVICE_NAME
              value: grpc-server