---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: staging
spec:
  ingressClassName: external-ingress-nginx
  rules:
    - host: ilovek8s.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: otel-go
                port:
                  number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: otel-go
  namespace: staging
spec:
  selector:
    app: otel-go
  ports:
    - port: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-go
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-go
  template:
    metadata:
      labels:
        app: otel-go
    spec:
      containers:
        - name: otel-go
          image: hasannaber123/otel-go:latest
          ports:
            - containerPort: 8080
          env:
            - name: OTLP_ENDPOINT
              value: tempo.tempo:4317
            - name: OTEL_SERVICE_NAME
              value: test-service
