---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  namespace: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Main
      type: prometheus
      uid: prometheus
      url: http://prometheus-operated.monitoring:9090
      isDefault: false
      jsonData:
        manageAlerts: false
    - name: Tempo
      type: tempo
      url: http://tempo.tempo:3100
      isDefault: false
      jsonData:
        manageAlerts: false
        serviceMap:
          datasourceUid: 'prometheus'    
          apiVersion: 1
        nodeGraph:
          enabled: true